const express = require('express');
const router  = express.Router();
const ctrl    = require('./configuracion.controller');
const { autenticar } = require('../auth/auth.middleware');
const { authorize }  = require('../../shared/middleware/authorize');
const ADMIN = authorize('DIRECTOR','ADMIN','SUBDIRECTOR');
router.get('/',              autenticar,        ctrl.obtener);
router.post('/',             autenticar, ADMIN, ctrl.crear);
router.put('/:id',           autenticar, ADMIN, ctrl.actualizar);
router.patch('/:id/estado',  autenticar, ADMIN, ctrl.toggleEstado);
module.exports = router;